# Hyperparameters for Decoder Training
learning_rate: 0.0001
batch_size: 512
epochs: 400
steps_per_epoch: 100
validation_split: 0.1
device: "cuda"

# Data alignment
input_window_size: 1  # Number of successive RGC timepoints to use for one frame reconstruction
target_frame_offset: "last" # Options: "last" (end of RGC temporal memory) or "center"
